// AGENTS.md — the tool-neutral agent context file (Codex, Cursor, Claude… read it), next to a short
// CLAUDE.md stanza that points to it (BACKLOG-AGENTIC §27.5, #98; DESIGN §27.3).
//
// Both files carry ONE uxc-owned block between `<!-- uxc:begin -->` and `<!-- uxc:end -->`. Whatever
// sits outside the markers is the author's and is never touched: an existing file keeps its text and
// gets the block appended; a file that already has the block gets only the block replaced. The block
// is rendered from package facts (the manifest) and nothing else, so it is deterministic: two runs
// on the same manifest write the same bytes. A per-checkout pin (`.uxc/target`) is deliberately NOT
// read — AGENTS.md is a tracked file and must not differ between clones.
import { prefixForms } from './naming.mjs';

export const BEGIN = '<!-- uxc:begin -->';
export const END = '<!-- uxc:end -->';

const fence = (lines) => [BEGIN, ...lines, END].join('\n');
const pf = (f) => `\`${f.pascal}\`/\`${f.camel}\`/\`${f.kebab}\`/\`${f.upper}\``;

/** The uxc block of AGENTS.md (markers included, no trailing newline). */
export function renderAgentsSection(manifest) {
  const m = manifest ?? {};
  const f = m.idPrefixes ?? prefixForms(m.code);
  const deps = Object.entries(m.dependencies ?? {}).sort((a, b) => a[0].localeCompare(b[0]));
  const of = m.extension?.of ?? null;
  const pinned = typeof m.agent?.target === 'string' ? m.agent.target : null;
  const depLine = ([code, d]) => `\`${code}\`${d?.slug && d.slug !== code ? ` (${d.slug})` : ''} \`${d?.versions ?? '*'}\``;

  const L = [
    `## Uxopian package \`${m.code}\` — ${m.name}`,
    '',
    '_Generated by uxc from `uxopian-project.json`; `uxc context --agents-md --write` refreshes this block. Edit outside the uxc markers only._',
    '',
    'A uxopian-package: FlowerDocs + Uxopian AI customizations managed by the `uxc` CLI.',
    '',
    `- code \`${m.code}\`${m.version ? ` · version ${m.version}` : ''} · manifest \`uxopian-project.json\` · catalog \`registry.json\` · sync state \`.uxc/state.json\``,
    '- resources live under `fd/`, `ai/`, `data/`; package tests under `tests/`',
    `- owned id prefixes: \`${f.pascal}\` (pascal: classes, handlers) · \`${f.camel}\` (camel: prompts, goals, beans) · \`${f.kebab}\` (kebab: script/guiconfig docs) · \`${f.upper}\` (upper: runtime ids)`,
  ];
  if (of) {
    const d = m.dependencies?.[of];
    L.push(`- EXTENDS \`${of}\`${d?.slug ? ` (${d.slug})` : ''}, versions \`${d?.versions ?? '*'}\` — this package adds to it and never edits it`);
  }
  const others = deps.filter(([c]) => c !== of);
  if (others.length) L.push(`- depends on: ${others.map(depLine).join(', ')}`);

  L.push(
    '',
    '### Operating rules',
    '',
    '1. ALL FlowerDocs / Uxopian AI server work goes through `uxc` — never ad-hoc HTTP scripts or curl deploys (cache clears, handler version rotation and the verified API mechanics live in the tool).',
    '2. Start every session with `uxc context`: package map, operating policy, pinned target, gotchas.',
    `3. Create ids ONLY under the owned prefixes above.${of ? ` Never under ${pf(prefixForms(of))} (the namespace of \`${of}\`): \`uxc verify\` refuses it (EXT_PRODUCT_RESOURCE, EXT_FOREIGN_RESOURCE, EXT_ROW_PREFIX…).` : ''}`,
    '4. Run `uxc verify` before every push (`push` runs it too — do not bypass it with `--ignore-lint`).',
    '5. Never guess an API shape. The verified mechanics are recorded in the learnings shipped with uxc (FLOWERDOCS-LEARNINGS.md, UXOPIAN-AI-LEARNINGS.md); find the section with `uxc help --search <term>`. Not recorded? Prove it on a throwaway `Zz*` object first.',
    pinned
      ? `6. This package is PINNED to target \`${pinned}\` (\`agent.target\`): never pass a different \`--target\`.`
      : '6. One checkout deploys to one instance: pin it (`"agent": { "target": "<name>" }` in the manifest, or `.uxc/target`) and never pass a different `--target`.',
    '7. Conflicts surface, they are never clobbered: look with `uxc diff <id>`, then decide `uxc pull` or `uxc push` per resource.',
    '',
    '### Day to day',
    '',
    '- `uxc status [--remote]` — drift between local files, the sync base and the server',
    '- `uxc add <kind> <Name>` — scaffold a resource (the templates carry the mechanics)',
    '- `uxc push --changed` / `uxc pull` — hash-synced deploy / backport',
    '- `uxc diff <id>` · `uxc explain <CODE>` · `uxc doctor --ready`',
    '- `uxc <command> --help` — flags and examples',
    '',
    '### Tests',
    '',
    `- \`uxc test --offline\` — the package tests under \`tests/\`, no server${of ? ' (keep the extension examples green)' : ''}`,
    '- `uxc verify` — offline lints (prefixes, include order, sizes, references)',
    '- `uxc test` — the same tests plus the live ones, against the target',
  );
  return fence(L);
}

/** The uxc block of CLAUDE.md: a pointer to AGENTS.md plus the Claude-only bits. */
export function renderClaudeSection(manifest) {
  const m = manifest ?? {};
  return fence([
    `## Uxopian package \`${m.code}\` — read AGENTS.md first`,
    '',
    '`AGENTS.md` holds this package\'s map, operating rules, command cheat-sheet and test commands',
    '(tool-neutral: Codex, Cursor and Claude read the same file). It applies here in full.',
    '',
    'Claude-specific: the `uxopian-client` skill and the `/ux-status`, `/ux-new`, `/ux-push`, `/ux-sync`,',
    '`/ux-smoke`, `/ux-export`, `/ux-import` slash commands wrap the same `uxc` commands',
    '(installed by `uxc install-claude`).',
  ]);
}

/**
 * Put `section` (a fenced block) into `existing` text: replace the uxc block when there is one,
 * append it otherwise; `header` starts a file that does not exist yet (existing == null).
 * CRLF files stay CRLF — the block is written in the file's own line endings; text OUTSIDE the
 * markers is kept byte for byte (a mixed-ending file keeps its bare-LF lines, #103).
 */
export function upsertSection(existing, section, header = '') {
  if (existing == null) return `${header}${section}\n`;
  const eol = /\r\n/.test(existing) ? '\r\n' : '\n';
  const sec = section.replace(/\r?\n/g, eol);
  const text = existing;
  const count = (m) => text.split(m).length - 1;
  const b = text.indexOf(BEGIN);
  const e = text.indexOf(END);
  const nb = count(BEGIN);
  const ne = count(END);
  // Only a WELL-FORMED block is ours to replace: exactly one begin, one end, in that order. Any
  // other combination (an end marker deleted by hand, a duplicated block, an end before the begin)
  // would make a replace swallow the user's text between stray markers — refuse and say where.
  if ((nb || ne) && !(nb === 1 && ne === 1 && b < e)) {
    throw new Error(`the uxc block markers are damaged (${nb}× ${BEGIN}, ${ne}× ${END}): `
      + 'keep exactly one begin/end pair (or delete both to get a fresh block), then re-run');
  }
  if (nb === 1) return text.slice(0, b) + sec + text.slice(e + END.length);
  const gap = text === '' || /\r?\n\r?\n$/.test(text) ? '' : /\r?\n$/.test(text) ? eol : eol + eol;
  return `${text}${gap}${sec}${eol}`;
}
